version: '3.2'

services:
#  producer:
#    build:
#       context: ./
#       dockerfile: producer.Dockerfile
#    links:
#      - mongo
#    environment:
#      WAIT_HOSTS: mongo:27017

#  results:
#    build:
#       context: ./
#       dockerfile: consumer.Dockerfile
#    links:
#      - mongo
#    environment:
#      WAIT_HOSTS: mongo:27017
      
  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    ports:
      - 5000:5000
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017  

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rooty
      ME_CONFIG_MONGODB_ADMINPASSWORD: passy

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rooty
      MONGO_INITDB_ROOT_PASSWORD: passy
