version: '3.2'

services:
  job:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: output
        target: /mount
    
volumes:
  output:
    
